### ISSUE TITLE
Nesting and indentation

### ISSUE THREAD

**Issue by aubreywullschleger** [krazii-chik/prj-rev-bwfs-dasmoto#1]
Great! Great job with the nesting and indentation of your HTML. The clear separation of your divs along with the clean nesting and indentation makes your code very easy to read. Keep it up!
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L9-L11
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L17
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L18-L23
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L24-L29

**Comment by krazii-chik** [comment]
Thank-you
