### ISSUE TITLE
Comments in HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [krazii-chik/prj-rev-bwfs-dasmoto#2]
Simplify! To make your code even easier to read I would consider wrapping each separate div in comments that describe the section of code, for example you could use (this is personal preference, and may help you practice making sure your elements are staying nested consistently):

```
        <!-- start frames section -->
        <div id="frames">
            <h2 class="title">Frames</h2>
            <img src="resources/frames.jpeg">
            <h3>Art Frames (assorted)</h3>
            <p>Assorted frames made of different material, including MDF, birchwood and PDE. Select frames can be sanded and painted according to your needs. <span class="prices">Starting at $2.00 / frame.</span></p>
        </div>
        <!-- end frames section -->
```

https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L17
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L18-L23
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L24-L29

**Comment by krazii-chik** [comment]
Thanks for the advice, I can see how the comments would make the code much clearer esp. for larger projects.
