### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [krazii-chik/prj-rev-bwfs-dasmoto#3]
Great! Awesome work using locally stored images! The use of these downloaded images makes sure that you aren't relying on an outside server and will help your page load faster. Great job!
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L14
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L20
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L26
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/main.css#L10

**Comment by krazii-chik** [comment]
Thank-you
