### ISSUE TITLE
Concise CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [krazii-chik/prj-rev-bwfs-dasmoto#4]
Great! Well done keeping your CSS concise! The only thing I would change would be grouping the selectors using `font-weight: bold;` then deleting the other instances of `font-weight: bold;`

https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/main.css#L7
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/main.css#L15
https://github.com/krazii-chik/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/main.css#L32

**Comment by krazii-chik** [comment]
Thank-you for your comments, selectors are still a little confusing and I sometimes need to refer back to lesson notes
