### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [krazii-chik/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:  
Really great work on this project! I love how easy your HTML and CSS are to read. They are concise and formatted wonderfully. I also appreciate your style choice for the header, it really grabs your attention!

A couple things to consider would be adding comments to make your HTML even easier to read and to group selectors for cutting down on repetitive code.

Next, as a challenge, I would research how to use responsive design techniques, like media queries, to make sure your page is responsive at all screen widths. I think you are ready for this challenge based on your great work with this project.
See here: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and here: https://css-tricks.com/snippets/css/media-queries-for-standard-devices/ to learn about media queries.

**Comment by krazii-chik** [comment]
Thank-you Aubrey, I appreciate your feedback and I am just about to check out those links
